services:
  api:
    build: app/
    ports:
      - 8000:8000

  mongo_db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  elasticsearch_db:
    image: elasticsearch:8.10.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node